eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 9999

spring:
  datasource:
    name: pay
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.167.3.151:3306/new_retail_db
    username: wuye
    password: wuye
    # 使用druid数据源
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    #filters 去掉wall，取消防御sql注入
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    logSlowSql: true
  application:
    name: service-open
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
  http:
    encoding:
      charset: UTF-8
      enabled: true

yzy:
  wechat:
    appid: wx111f1b7437e708dd
    appsecret: e12860f0ce3d177f39e2160a0c8286c1
  paywechat:
    appid: wx111f1b7437e708dd
    appsecret: e12860f0ce3d177f39e2160a0c8286c1

logging:
  config: classpath:logback.xml

#开启驼峰转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true








