eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 9999

spring:
  application:
    name: service-open
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
  http:
    encoding:
      charset: UTF-8
      enabled: true

yzy:
  wechat:
    appid: wx111f1b7437e708dd
    appsecret: e12860f0ce3d177f39e2160a0c8286c1
  paywechat:
    appid: wx111f1b7437e708dd
    appsecret: e12860f0ce3d177f39e2160a0c8286c1

logging:
  config: classpath:logback.xml


